package corbamodule;


/**
* corbamodule/commonOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from client.idl
* Saturday, November 4, 2017 1:53:13 AM EDT
*/

public interface commonOperations 
{
  boolean createroom (String rno, String date, String timeslot);
  boolean deleteroom (String rno, String date, String timeslot);
  String bookroom (String campusName, String rno, String date, String timeslot, String UID);
  String getAvailableTimeSlot (String date);
  String cancelBooking (String bookingID, String userid);
  String changeReservation (String studentid, String booking_id, String new_date, String new_campus_name, String new_room_no, String new_time_slot);
} // interface commonOperations
