package corbamodule;


/**
* corbamodule/common.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from client.idl
* Saturday, November 4, 2017 1:53:13 AM EDT
*/

public interface common extends commonOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface common
