package corbamodule;


/**
* corbamodule/commonHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from client.idl
* Saturday, November 4, 2017 1:53:13 AM EDT
*/

abstract public class commonHelper
{
  private static String  _id = "IDL:corbamodule/common:1.0";

  public static void insert (org.omg.CORBA.Any a, corbamodule.common that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static corbamodule.common extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (corbamodule.commonHelper.id (), "common");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static corbamodule.common read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_commonStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, corbamodule.common value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static corbamodule.common narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof corbamodule.common)
      return (corbamodule.common)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      corbamodule._commonStub stub = new corbamodule._commonStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static corbamodule.common unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof corbamodule.common)
      return (corbamodule.common)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      corbamodule._commonStub stub = new corbamodule._commonStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
