package corbamodule;

/**
* corbamodule/commonHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from client.idl
* Saturday, November 4, 2017 1:53:13 AM EDT
*/

public final class commonHolder implements org.omg.CORBA.portable.Streamable
{
  public corbamodule.common value = null;

  public commonHolder ()
  {
  }

  public commonHolder (corbamodule.common initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = corbamodule.commonHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    corbamodule.commonHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return corbamodule.commonHelper.type ();
  }

}
